services:
  download-redisbungee:
    image: alpine:latest
    entrypoint: /bin/sh -c 'apk add --no-cache curl jq && curl -L -o RedisBungee.jar $(curl -s https://api.github.com/repos/ProxioDev/ValioBungee/releases/latest | jq -r ".assets[] | select(.name | contains(\"-Bungee\")) | .browser_download_url") && cp *.jar ./1 && cp *.jar ./2 && exit 0'
    volumes:
      - ./proxy/1/plugins:/proxy-plugins/1
      - ./proxy/2/plugins:/proxy-plugins/2
    working_dir: /proxy-plugins
  redis:
    hostname: redis
    depends_on:
      download-redisbungee:
        condition: service_completed_successfully
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --appendonly yes --replica-read-only no --save 60 1 --loglevel warning
    volumes:
     - redis-data:/server
  proxy-1:
    depends_on:
    - redis
    hostname: proxy-1
    image: itzg/mc-proxy
    tty: true
    stdin_open: true
    ports:
      - "25565:25577"
    environment:
      FORCE_REDOWNLOAD: "true"
      TYPE: "BUNGEECORD"
    volumes:
      - ./proxy/1:/server
  proxy-2:
    depends_on:
    - redis
    hostname: proxy-2
    image: itzg/mc-proxy
    tty: true
    stdin_open: true
    ports:
      - "25566:25577"
    environment:
      FORCE_REDOWNLOAD: "true"
      TYPE: "BUNGEECORD"
    volumes:
      - ./proxy/2:/server
  backend-a:
    hostname: backend-a
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      TYPE: "PAPER"
      VERSION: "latest"
      EULA: "TRUE"
      FORCE_REDOWNLOAD: "true"
      SERVER_NAME: "backend-a"
      ALLOW_NETHER: "false"
      GAMEMODE: "creative"
      SPIGET_RESOURCES: "25391"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./server/a:/data
  backend-b:
    hostname: backend-b
    image: itzg/minecraft-server
    tty: true
    stdin_open: TRUE
    environment:
      TYPE: "PAPER"
      VERSION: "latest"
      EULA: "TRUE"
      FORCE_REDOWNLOAD: "true"
      SERVER_NAME: "backend-a"
      ALLOW_NETHER: "false"
      GAMEMODE: "creative"
      SPIGET_RESOURCES: "25391"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./server/b:/data

volumes:
  redis-data: