services:
  setup:
    image: alpine:latest
    entrypoint: |
      /bin/sh -c 'apk add --no-cache curl curl jq && 
      curl -L -O $(curl -s https://api.github.com/repos/ProxioDev/ValioBungee/releases/latest | 
      jq -r ".assets[] | select(.name | contains(\"-Bungee\")) | .browser_download_url") && 
      cp *.jar ./proxy/plugins && 
      rm -r ./*.jar &&
      curl -s "https://ci.wea-ondara.net/job/BungeePerms/lastSuccessfulBuild/api/json" |
      jq -r ".artifacts[] | select(.fileName | contains(\"original\") | not) | .relativePath" | 
      xargs -I {} curl -O "https://ci.wea-ondara.net/job/BungeePerms/lastSuccessfulBuild/artifact/{}" &&
      cp *.jar ./common/plugins &&
      cp -r /proxy-plugins/backend/* /proxy-plugins/a/ &&
      cp -r /proxy-plugins/backend/* /proxy-plugins/b/ &&
      cp -r /proxy-plugins/common/* /proxy-plugins/a/ &&
      cp -r /proxy-plugins/common/* /proxy-plugins/b/ &&
      cp -r /proxy-plugins/common/* /proxy-plugins/1/ &&
      cp -r /proxy-plugins/common/* /proxy-plugins/2/ &&
      cp -r /proxy-plugins/proxy/* /proxy-plugins/1/ &&
      cp -r /proxy-plugins/proxy/* /proxy-plugins/2/ &&
      exit 0'
    volumes:
      - ./.defaults/backend:/proxy-plugins/backend
      - ./.defaults/proxy:/proxy-plugins/proxy
      - ./.defaults/common:/proxy-plugins/common
      - ./proxy/1:/proxy-plugins/1
      - ./proxy/2:/proxy-plugins/2
      - ./backend/a:/proxy-plugins/a
      - ./backend/b:/proxy-plugins/b
    working_dir: /proxy-plugins
  redis:
    hostname: redis
    depends_on:
      setup:
        condition: service_completed_successfully
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --appendonly yes --replica-read-only no --save 60 1 --loglevel warning
    volumes:
     - redis-data:/server
  proxy-1:
    depends_on:
    - redis
    hostname: proxy-1
    image: itzg/mc-proxy
    tty: true
    stdin_open: true
    ports:
      - "25565:25577"
    environment:
      FORCE_REDOWNLOAD: "true"
      TYPE: "BUNGEECORD"
      CFG_ID: "proxy-1"
      CFG_MOTD: |
      proxy-1* (:25565)
      proxy-2  (:25566)
    volumes:
      - ./proxy/1:/server
  proxy-2:
    depends_on:
    - redis
    hostname: proxy-2
    image: itzg/mc-proxy
    tty: true
    stdin_open: true
    ports:
      - "25566:25577"
    environment:
      FORCE_REDOWNLOAD: "true"
      TYPE: "BUNGEECORD"
      CFG_ID: "proxy-2"
      CFG_MOTD: |
      proxy-1  (:25565)
      proxy-2* (:25566)
    volumes:
      - ./proxy/2:/server
  backend-a:
    depends_on:
    - redis
    hostname: backend-a
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      TYPE: "PAPER"
      VERSION: "latest"
      EULA: "TRUE"
      FORCE_REDOWNLOAD: "true"
      SERVER_NAME: "backend-a"
      ALLOW_NETHER: "false"
      GAMEMODE: "creative"
      SPIGET_RESOURCES: "25391"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./backend/a:/data
  backend-b:
    depends_on:
    - redis
    hostname: backend-b
    image: itzg/minecraft-server
    tty: true
    stdin_open: TRUE
    environment:
      TYPE: "PAPER"
      VERSION: "latest"
      EULA: "TRUE"
      FORCE_REDOWNLOAD: "true"
      SERVER_NAME: "backend-a"
      ALLOW_NETHER: "false"
      GAMEMODE: "creative"
      SPIGET_RESOURCES: "25391"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./backend/b:/data

volumes:
  redis-data: