permissions:
  default:
  - *
servers:
  a:
    motd: 'backend/a'
    address: backend-a:25565
    restricted: false
  b:
    motd: 'backend/b'
    address: backend-b:25565
    restricted: false
listeners:
  motd: 'proxy-1'
  priorities:
  - b
  - a
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 100
ip_forward: true
